backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "microblog"
    label: "Mis Tweets"
    folder: "microblog/posts"
    extension: "json"
    format: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: date
    fields:
      - { label: "Título de la Transmisión", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen sutil o Descripción", name: "description", widget: "string" }
      - { label: "Cuerpo del Comunicado (Texto)", name: "body", widget: "text" }
      - { label: "Foto opcional", name: "foto", widget: "image", required: false }
      - { label: "Código de Video incrustado", name: "video", widget: "text", required: false }
