backend:
  name: git-gateway
  branch: main # Cambiala si tu rama principal se llama 'master'

local_backend: true # Te permite probar el panel en localhost

media_folder: "assets/uploads" # Dónde se guardarán las imágenes que subas
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Publicaciones de la Brecha"
    folder: "blog/posts" # Los artículos se guardarán en blog/posts/
    create: true
    slug: "{{slug}}"
    extension: "json" # Guardamos como JSON para leerlo fácil con JS
    format: "json"
    fields:
      - { label: "Título de la Transmisión", name: "title", widget: "string" }
      - { label: "Fecha de Inyección", name: "date", widget: "datetime" }
      - { label: "Imagen de Portada", name: "image", widget: "image", required: false }
      - { label: "Resumen Corto", name: "description", widget: "string" }
      - { label: "Cuerpo del Mensaje", name: "body", widget: "markdown" }