backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "microblog"
    label: "Mis Tweets"
    folder: "microblog/posts"
    extension: "json"
    format: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: date
    fields:
      - { label: "Nombre deñ equipo", name: "title", widget: "string" }
      - { label: "Fecha (con el boton now se pone automaticamente)", name: "date", widget: "datetime" }
      - { label: "Resumen sutil o Descripción", name: "description", widget: "string" }
      - { label: "Aca describis un toque lo que quieras", name: "body", widget: "text" }
      - { label: "Foto opcional", name: "foto", widget: "image", required: false }
